name: Deploy to Heroku
on:
  push:
    branches:
      - main
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Init secrets
        run: |
          git checkout -b heroku
          API_KEY=convertio-conversion-source-exchangeratesapi/src/main/resources/api.key
          echo ${{ secrets.EXCHANGE_RATES_API_KEY }} > $API_KEY
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -f $API_KEY
          git commit -m "Secrets applied"
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
          dontautocreate: true
          dontuseforce: true
          healthcheck: https://alexander-shelyugov-convertio.herokuapp.com/actuator/health
