name: Deploy to Heroku
on:
  push:
    branches:
      - main
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: heroku
          usedocker: false
          dontautocreate: true
          healthcheck: https://alexander-shelyugov-convertio.herokuapp.com/actuator/health
